# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: password
#  host: host.docker.internal
  host: mysql
  port: 3306

default-legacy: &default-legacy
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: secret
  host: postgresql
  port: 5432


development-legacy:
  <<: *default-legacy
  database: rspec_boilerplate_legacy_development

development:
  <<: *default
#  database_url: mysql2://root:password@host.docker.internal:3306/rspec_boilerplate_development
#  database_url: mysql2://root:password@mysql:3306/rspec_boilerplate_development
#  database_url: mysql2://root:password@localhost:6033/rspec_boilerplate_development
  database: rspec_boilerplate_development


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: rspec_boilerplate_test
  host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

production:
  <<: *default
  database: storage/production.sqlite3
